In [ ]:
import duckdb
import pandas as pd

con = duckdb.connect("C:\Dash_prod_online\data\warehouse\producao.duckdb")
#con = duckdb.connect("C:/Users/arg-mario.filho/data_project/Dashboard_producao_online/data/warehouse/paradas.duckdb")

IOException: IO Error: Cannot open file "\\?\C:\Users\arg-mario.filho\data_project\Dashboard_producao_online\data\warehouse\producao.duckdb": O sistema não pode encontrar o caminho especificado.

In [130]:
df = pd.DataFrame(con.execute("SELECT * FROM producao_consulta").df())
df.to_csv("C:/Users/arg-mario.filho/Downloads/arquivo.csv", sep=";", index=False)
con.close()

In [126]:
con.close()

In [122]:
con.execute("SHOW TABLES").df()

Empty DataFrame
Columns: [name]
Index: []

In [114]:
con.execute("DROP TABLE IF EXISTS producao_historico")

In [115]:
con.close()

In [89]:
df

NameError: name 'df' is not defined

In [106]:
con.execute("SELECT * FROM producao_consulta").df()

,Dia,LinhaProducao,HoraInicial,HoraFinal,OEE,Produto,Formato,CicloPadrao,CicloMedio,MetaHoraSistema,ProducaoBruta,ProducaoBrutaCx,Paradas,TempoTotalParada,DataCarga
0,2026-03-18,PET 500/1000ml,15:00:00,15:36:00,25.91,070200801003 - SUCO MARACUJA DAFRUTA 12X500 PE...,12X500,400.0,NaN,5483,1421,118.416667,CM1037 - Falha no envolvimento do filme | CM10...,00:12:25,2026-03-18 15:36:59.372895
1,2026-03-18,SIG 200/150ML - CFA 112,15:00:00,15:36:00,82.75,060101201030 - REFRESCO SABORIZADO UVA M DAFRU...,27X200,304.0,309.516,7220,5980,221.481481,999999999 - Parada Nao Informada,00:05:46,2026-03-18 15:36:59.372895
2,2026-03-18,SIG 1000/750ML,15:00:00,15:36:00,0.00,060105302014 - NATURAL TEA CHA BRANCO PITAYA E...,12X1000,406.0,0.000,0,0,0.000000,CP3001 - ...,00:36:27,2026-03-18 15:36:59.372895
3,2026-03-18,SIG 200/150ml - CFA 124,15:00:00,15:36:00,78.38,060100602096 - MAGUARY FRUIT SHOOT LARANJA HB ...,27X150,150.0,174.229,14675,11503,426.037037,CM4015 - Falha na Selagem das abas | CM4043 - ...,00:03:17,2026-03-18 15:36:59.372895
4,2026-03-18,PET,15:00:00,15:36:00,86.89,060200801005 - CONC LIQ P/ REF MARACUJA DAFRUT...,6X1000,257.0,271.164,8416,7309,1218.166667,999 - Microparada | 999999999 - Parada Nao Inf...,00:03:35,2026-03-18 15:36:59.372895
5,2026-03-18,SIG I,15:00:00,15:36:00,70.93,060100402021 - PPB MAGUARY GOIABA 12X1000ML,12X1000,304.0,306.841,7196,5102,425.166667,GM1057 - Falha no magazine de pallets | GM1028...,00:10:22,2026-03-18 15:36:59.372895
6,2026-03-18,SIG II,15:00:00,15:36:00,0.00,060100102021 - PPB MAGUARY ABACAXI 12X1000ML,12X1000,304.0,0.000,7267,0,0.000000,GM2017 - Falha na Transferęncia para Esteira d...,00:36:49,2026-03-18 15:36:59.372895
7,2026-03-18,SIG III,15:00:00,15:36:00,46.03,060101202100 - PPB MAGUARY UVA B. CALORIA 27X2...,27X200,150.0,157.085,14715,6826,252.814815,GM3109 - Falha na codificaçăo secundária | GM3...,00:19:03,2026-03-18 15:36:59.372895
8,2026-03-18,SIG IV,15:00:00,15:36:00,82.36,060101202100 - PPB MAGUARY UVA B. CALORIA 27X2...,27X200,304.0,312.173,7261,6009,222.555556,GM6042 - Falha no esquadrejamento das embalage...,00:05:41,2026-03-18 15:36:59.372895
9,2026-03-18,PET ZEGLA,15:00:00,15:36:00,39.25,060200301011 - CONC LIQ P/ REF CAJU DAFRUTA 6X...,6X1000,458.0,509.894,4757,1881,313.500000,DM1122 - Falha no sopro | 999 - Microparada | ...,00:20:26,2026-03-18 15:36:59.372895
10,2026-03-18,LINHA TETRA 1000 ML,15:00:00,15:36:00,57.16,060100301018 - NECTAR CAJU DAFRUTA REFORMULACA...,12X1000,514.0,520.265,4293,2453,204.416667,DM3151 - Falha na formaçăo da caixa | 999 - Mi...,00:15:30,2026-03-18 15:36:59.372895
11,2026-03-18,LINHA-TETRA-200,15:00:00,15:36:00,0.00,060100801028 - REFRESCO SABORIZADO MARACUJA M ...,27X200,400.0,0.000,0,0,0.000000,DP1001 - S...,00:36:38,2026-03-18 15:36:59.372895
12,2026-03-18,LINHA SIG 1000 ML,15:00:00,15:36:00,0.00,060101201029 - REFRESCO SABORIZADO UVA M DAFRU...,12X1000,304.0,0.000,7195,0,0.000000,999999999 - Parada Nao Informada,00:36:27,2026-03-18 15:36:59.372895
13,2026-03-18,LINHA DE ENVASE PPB SIG 200ML,15:00:00,15:36:00,51.76,060101201030 - REFRESCO SABORIZADO UVA M DAFRU...,27X200,304.0,373.134,7288,3795,140.555556,999999999 - Parada Nao Informada | DM5027 - Fa...,00:13:28,2026-03-18 15:36:59.372895

In [119]:
df = pd.DataFrame(con.execute("SELECT * FROM producao_consulta").df())
df.to_csv("C:/Users/arg-mario.filho/Downloads/arquivo.csv", sep=";", index=False)

In [123]:
con.close()